import Head from "next/head"
import Navbar from "./navbar"
import Footer from './footer'

export default function Layout({ children }) {  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container mx-auto px-4 md:px-8 lg:px-12 py-4 md:py-8 lg:py-10 lg:w-7/12 text-gray-600 text-base">
        <Navbar></Navbar>
        <main>
          {children}
        </main>
        <Footer />
      </div>
    </>
  )
}